from __future__ import annotations

from typing import List

from .models import SourceConfig


DEFAULT_SOURCES: List[SourceConfig] = [
    SourceConfig(
        source_name="brave_high_search",
        source_type="search",
        priority="P0",
        lane="high",
        method="brave_search",
        url="https://api.search.brave.com/res/v1/web/search",
        alert_threshold_minutes=120,
    ),
    SourceConfig(
        source_name="serpapi_high_search",
        source_type="search",
        priority="P0",
        lane="high",
        method="serpapi",
        url="https://serpapi.com/search.json",
        alert_threshold_minutes=120,
    ),
    SourceConfig(
        source_name="gnews_high_news",
        source_type="news",
        priority="P0",
        lane="high",
        method="gnews",
        url="https://gnews.io/api/v4/search",
        alert_threshold_minutes=120,
    ),
    SourceConfig(
        source_name="google_news_high_rss",
        source_type="news",
        priority="P0",
        lane="high",
        method="rss",
        url="google-news://high",
        alert_threshold_minutes=120,
    ),
    SourceConfig(
        source_name="cpsc_recalls",
        source_type="cpsc",
        priority="P0",
        lane="high",
        method="api",
        url="http://www.saferproducts.gov/RestWebServices/Recall?format=json",
        alert_threshold_minutes=120,
    ),
    SourceConfig(
        source_name="brave_regular_search",
        source_type="search",
        priority="P1",
        lane="regular",
        method="brave_search",
        url="https://api.search.brave.com/res/v1/web/search",
        alert_threshold_minutes=360,
    ),
    SourceConfig(
        source_name="serpapi_regular_search",
        source_type="search",
        priority="P1",
        lane="regular",
        method="serpapi",
        url="https://serpapi.com/search.json",
        alert_threshold_minutes=360,
    ),
    SourceConfig(
        source_name="gnews_regular_news",
        source_type="news",
        priority="P1",
        lane="regular",
        method="gnews",
        url="https://gnews.io/api/v4/search",
        alert_threshold_minutes=360,
    ),
    SourceConfig(
        source_name="google_news_regular_rss",
        source_type="news",
        priority="P1",
        lane="regular",
        method="rss",
        url="google-news://regular",
        alert_threshold_minutes=360,
    ),
    SourceConfig(
        source_name="prnewswire_rss",
        source_type="news",
        priority="P1",
        lane="regular",
        method="generic_rss",
        url="https://www.prnewswire.com/rss/news-releases-list.rss",
        alert_threshold_minutes=360,
    ),
]
